### ISSUE TITLE
Create the Text Processing Pipeline Stage

### ISSUE THREAD

**Issue by battila7** [underdocs/underdocs#63]
## Brief

Create a new Stage which will execute so-called text processors.

## Background

This is a subtask of #54.

On today's (20 August 2020) Discord call, I mentioned that we should start by creating a Markdown processor stage. If you look at the `MarkdownProcessor` interface at https://github.com/underdocs/plugin-refactor#pluginok , you can see that it has a `before` and `after` function. To make things easier to implement and grasp, I figured that we should separate the `before` and `after` functions into two plugins:

  * the before phase becomes the text processing stage, since it works on raw comment text,
  * the after phase will stay in the Markdown processing stage.

## Task

This issue breaks down into three smaller tasks:

  * [ ] Establish the interface of the text processor plugins.
  * [ ] Implement a new pipeline stage which executes the text processors. 
  * [ ] Test the stage.

### Establish the Interface

First, we should make it clear what text processors should do. Given a raw comment text, they execute some transformations and output a new, possibly modified comment text:

~~~~
original comment text -> Text Processor Plugin -> possibly modified comment text
~~~~

The above idea translates to something like this in Kotlin:

~~~~Kotlin
interface TextProcessorPlugin {
  fun process(context: Context): StepOutput<String?>

  class Context(val element: CodeElement, rawComment: String?)
}
~~~~

Where:

  * We use the `StepOutput` wrapper type in the return type to optionally signal that processing should halt.
  * Introducing the `Context` class makes the the signature of the `process` function easier to read.
  * `CodeElement` is the actual code element that is being pushed through the pipeline.

Note, that the above code is not necessarily the interface you should work with, but just an idea.

### Implement the new Stage

The stage should operate as follows. Given a code element, the stage should sequentially execute each text processing plugin on the comment of the code element. If a code element has commented members (for example, enums), make sure to execute the plugins on the member comments as well. You might want to use the [Visitor pattern](https://sourcemaking.com/design_patterns/visitor) to correctly handle the different code elements.

When implementing the new stage, please adhere to the following requirements:

  * The stage does not need to catch exceptions thrown by text processing plugins.
  * If any of the plugins signals that processing should be aborted, then propagate this signal to the pipeline.

Translating the above to Kotlin:

~~~~Kotlin
class TextProcessorStage(private val plugins: List<TextProcessorPlugin>) : Stage<TextProcessorStage.Input, TextProcessorStage.Output> {
  fun process(input: Input): StageOutput<Output> {
    // Convert the Input into Output using the plugins.
  }

  class Input(val codeElement: CodeElement)

  class Output(val codeElement: CodeElement, val processedComment: ProcessedComment)
}

class ProcessedComment(val elementComment: String?, val memberComments: Map<String, String>)
~~~~

### Test the Stage

Testing is not really a separate task, but belongs to the previous one, but I decided to put more emphasize on it.

Please write a test, to ensure that the stage

  * can execute multiple plugins,
  * signals halt if a plugins signals so,
  * handles member comments correctly.

You should use dummy plugin implementations that were created just for the test.

## Dependencies

Agree with @palmarcell on 

  * the interface of the stages,
  * the input of this stage (as this is the first stage in the code pipeline).
